server:
  port: 8082

spring:
  application:
    name: news-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    bootstrap:
      enabled: false

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  packages-to-scan: com.newnormallist.newsservice.news.controller