spring:
  application:
    name: newsletter-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    bootstrap:
      enabled: false
  main:
    allow-bean-definition-overriding: true
    # feignclient bean override 설정
server:
  port: 8085
  # port 설정
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Actuator 엔드포인트 노출 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# 로깅 설정
logging:
  level:
    com.newsletterservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"