server:
  port: 8086

spring:
  application:
    name: tooltip-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    bootstrap:
      enabled: false

  cache:
    type: redis
    redis:
      time-to-live: 24h
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379
